name: Trails
version: '${project.version}'
main: wihy.trails.Trails
api-version: 1.19
authors: [ Wihy ]
description: Plugin to create trails

commands:
  trails:
    description: opens the trails gui
  start:
    description: start the trails
